version: '2'

volumes:
  postgres:
    driver: local
  test-postgres:
    driver: local

services:

  web:
    build: .
    expose:
      - 3000
      - 7000
    ports:
      - 3000:3000
      - 7000:7000
    volumes:
      - .:/usr/src/app

  # The backing database.
  postgres:
    image: postgres:9.6
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    networks:
      default:
    ports:
      - 5432
    volumes:
      - postgres:/var/lib/postgresql/data

  # The backing test database.
  test-postgres:
    image: postgres:9.6
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=test-postgres
    networks:
      default:
    ports:
      - 5432
    volumes:
      - test-postgres:/var/lib/postgresql/data

